version: 0.0
os: linux
files:
  - source: /
    destination: /home/webapp/takecho-ec

permissions:
  - object: /home/webapp/takecho-ec
    owner: webapp
    group: webapp

hooks:
  AfterInstall:
    - location: ./src/scripts/after_install.sh
      timeout: 60
      runas: webapp
