version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
    ports:
      - 5173:5173

  web:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=phper
      - PMA_PASSWORD=secret
    links:
      - db
    ports:
      - 8081:80
    volumes:
      - /sessions

volumes:
  db-store:
