version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.21-node
        environment:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_DATABASE: testing
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_HOST: '%'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          TZ: Asia/Tokyo
    
    steps:
      - checkout
      - run:
          name: pwd && ls -a
          command: pwd && ls -a

      # PHP関連パッケージのインストール
      - restore_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
      - run: cd src && composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
          paths:
            - vendor
            
      # JavaScript関連パッケージのインストール
      - restore_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
      - run: 
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              cd src && npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
          paths:
            - node_modules

      - run: sleep 60

      # マイグレーション
      - run: cd src && php artisan migrate

      # アセットのビルド
      - run:
          name: npm run build
          command: cd src && npm run build

      # テストの実行
      - run: 
          name: PHP test
          command: cd src && php artisan test
          requires: docker
