version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.2.8
    steps:
      - checkout

      # PHP関連パッケージのインストール
      - restore_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
      - run: cd /src && composer install -n --prefer-dist

      - name: pwd && ls -a
        run: pwd && ls -a

      - save_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
          paths:
            - vender
            
      # JavaScript関連パッケージのインストール
      - restore_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
      - run: 
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
               cd /src && npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
          paths:
            - node_modules

      - run: npm run dev
      - run: 
          name: php test
          command: cd /src && ./vendor/bin/phpunit
