version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.21-node
    
    steps:
      - checkout
      - run:
          name: pwd && ls -a
          command: pwd && ls -a

      # PHP関連パッケージのインストール
      - restore_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
      - run: cd src && composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "src/composer.lock" }}
          paths:
            - vender
            
      # JavaScript関連パッケージのインストール
      - restore_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
      - run: 
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
               cd src && npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "src/package-lock.json" }}
          paths:
            - node_modules

      - run: cd src && LARAVEL_BYPASS_ENV_CHECK=1 npm run dev
      - run: 
          name: php test
          command: cd src && ./vendor/bin/phpunit
