version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.2.8
    steps:
      - checkout
      - run: sudo composer self-update --1

      # PHP関連パッケージのインストール
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vender
            
      # JavaScript関連パッケージのインストール
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run: 
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: npm run dev
      - run: 
          name: php test
          command: cd /src && ./vendor/bin/phpunit
